name: Video 165FPS Processor
on:
  push:
    paths:
      - 'input/**'

jobs:
  boost_fps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Process Video
        run: |
          mkdir -p output
          ffmpeg -i input/* -filter:v "minterpolate=fps=165:mi_mode=mci" -c:a copy output/result.mp4

      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: 165FPS-Video
          path: output/result.mp4
